In [185]:
import pandas as pd
import numpy as np

### Data Loading

In [186]:
file_path ="Analytics Position Case Study.xlsx"

deposit = pd.read_excel(file_path, sheet_name = "Deposit Data", skiprows=3)
withdrawal = pd.read_excel(file_path, sheet_name = "Withdrawal Data", skiprows=3)
gameplay = pd.read_excel(file_path, sheet_name = "User Gameplay data", skiprows=3)

### Data Understanding

In [187]:
deposit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17438 entries, 0 to 17437
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   User Id   17438 non-null  int64
 1   Datetime  17438 non-null  object
 2   Amount    17438 non-null  int64
dtypes: int64(2), object(1)
memory usage: 408.8+ KB

In [188]:
withdrawal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3566 entries, 0 to 3565
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   User Id   3566 non-null   int64
 1   Datetime  3566 non-null   object
 2   Amount    3566 non-null   int64
dtypes: int64(2), object(1)
memory usage: 83.7+ KB

In [189]:
gameplay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355266 entries, 0 to 355265
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   User ID       355266 non-null  int64
 1   Games Played  355266 non-null  int64
 2   Datetime      355266 non-null  object
dtypes: int64(2), object(1)
memory usage: 8.1+ MB

In [190]:
deposit.dtypes

User Id      int64
Datetime    object
Amount       int64
dtype: object

In [191]:
withdrawal.dtypes

User Id      int64
Datetime    object
Amount       int64
dtype: object

In [192]:
gameplay.dtypes

User ID          int64
Games Played     int64
Datetime        object
dtype: object

In [193]:
deposit.columns

Index(['User Id', 'Datetime', 'Amount'], dtype='object')

In [194]:
withdrawal.columns

Index(['User Id', 'Datetime', 'Amount'], dtype='object')

In [195]:
deposit.head()

   User Id             Datetime  Amount
0      357  2022-01-10 00:03:00    2000
1      776  2022-01-10 00:03:00    2500
2      492  2022-01-10 00:06:00    5000
3      803  2022-01-10 00:07:00    5000
4      875  2022-01-10 00:09:00    1500

In [196]:
withdrawal.head()

   User Id             Datetime  Amount
0      190  2022-01-10 00:03:00    5872
1      159  2022-01-10 00:16:00    9540
2      164  2022-01-10 00:24:00     815
3      946  2022-01-10 00:29:00   23000
4      763  2022-01-10 00:40:00    9473

In [197]:
gameplay.head()

   User ID  Games Played             Datetime
0      851             1  2022-01-10 00:00:00
1      717             1  2022-01-10 00:00:00
2      456             1  2022-01-10 00:00:00
3      424             1  2022-01-10 00:00:00
4      845             1  2022-01-10 00:00:00

In [198]:
deposit.describe()

            User Id         Amount
count  17438.000000   17438.000000
mean     513.066005    5492.185400
std      290.101986   12046.364959
min        1.000000      23.000000
25%      270.000000     800.000000
50%      532.000000    2000.000000
75%      760.000000    5000.000000
max      999.000000  400400.000000

In [199]:
withdrawal.describe()

           User Id        Amount
count  3566.000000  3.566000e+03
mean    509.116657  2.355010e+04
std     305.839395  5.359007e+04
min       2.000000  1.000000e+02
25%     212.000000  3.300000e+03
50%     511.500000  8.000000e+03
75%     795.000000  2.000000e+04
max     992.000000  1.100000e+06

In [200]:
gameplay.describe()

             User ID   Games Played
count  355266.000000  355266.000000
mean      542.417130       1.000003
std       279.409789       0.001678
min         0.000000       1.000000
25%       300.000000       1.000000
50%       582.000000       1.000000
75%       765.000000       1.000000
max       999.000000       2.000000

In [201]:
deposit.isnull().sum()

User Id     0
Datetime    0
Amount      0
dtype: int64

In [202]:
withdrawal.isnull().sum()

User Id     0
Datetime    0
Amount      0
dtype: int64

In [203]:
gameplay.isnull().sum()

User ID         0
Games Played    0
Datetime        0
dtype: int64

In [204]:
deposit.duplicated().sum()

np.int64(1)

### Data Cleaning

#### Cleaning column names, removing duplicates, and handling datatypes.

In [205]:
gameplay.rename(columns = {'User ID': 'User Id'}, inplace = True)

In [206]:
deposit = deposit.drop_duplicates(subset = ['User Id', 'Datetime', 'Amount'])

In [207]:
withdrawal.duplicated().sum()

np.int64(0)

In [208]:
gameplay.duplicated().sum()

np.int64(13736)

In [209]:
gameplay = gameplay.drop_duplicates(subset = ['User Id', 'Games Played', 'Datetime'])

In [210]:
gameplay.duplicated().sum()

np.int64(0)

In [211]:

deposit['Datetime'] = pd.to_datetime(deposit['Datetime'], errors = 'coerce')
withdrawal['Datetime'] = pd.to_datetime(withdrawal['Datetime'], errors = 'coerce')
gameplay['Datetime'] = pd.to_datetime(gameplay['Datetime'], errors = 'coerce')

### Feature Engineering

In [212]:
# created time slots (S1 and S2) 
# Extracted date from time stamp

In [213]:
def get_slot(hour):
    if hour < 12:
        return "S1"
    else:
        "S2"

In [214]:
# create slot 
deposit['Slot'] = deposit['Datetime'].dt.hour.apply(get_slot)
withdrawal['Slot'] = withdrawal['Datetime'].dt.hour.apply(get_slot)
gameplay['Slot'] = gameplay['Datetime'].dt.hour.apply(get_slot)

In [215]:
# extract date
deposit['Date'] = deposit['Datetime'].dt.date
withdrawal['Date'] = withdrawal['Datetime'].dt.date
gameplay['Date'] = gameplay['Datetime'].dt.date

### Aggregation

In [216]:
# Aggregatin data at user id, date, and slot level

In [217]:
deposit_summary = deposit.groupby(['User Id', 'Date', 'Slot']).agg(deposit_amount = ('Amount', 'sum'), 
                                                                    deposit_count = ('Amount', 'count')
                                                                   ).reset_index()

In [218]:
deposit_summary.head()

   User Id        Date Slot  deposit_amount  deposit_count
0        2  2022-06-10   S1           40000              1
1        2  2022-08-10   S1           45000              2
2        2  2022-10-23   S1            5000              1
3        2  2022-11-10   S1           10000              1
4        2  2022-12-10   S1           40000              1

In [219]:
withdrawal_summary = withdrawal.groupby(['User Id', 'Date', 'Slot']).agg(withdrawal_amount = ('Amount', 'sum'), 
                                                                         withdrawal_count = ('Amount', 'count')
                                                                        ).reset_index()

In [220]:
withdrawal_summary.head()

   User Id        Date Slot  withdrawal_amount  withdrawal_count
0        2  2022-03-10   S1             117349                 1
1        2  2022-05-10   S1              36000                 1
2        2  2022-09-10   S1              11400                 1
3        2  2022-10-14   S1              46689                 1
4        2  2022-10-17   S1              27000                 1

In [221]:
gameplay_summary = gameplay.groupby(['User Id', 'Date', 'Slot']).agg(games_played = ('User Id', 'count')
                                                                    ).reset_index()

In [222]:
gameplay_summary.head()

   User Id        Date Slot  games_played
0        0  2022-06-10   S1             1
1        0  2022-10-10   S1             1
2        0  2022-10-17   S1             1
3        0  2022-10-22   S1             1
4        0  2022-10-23   S1             1

### Data Merging

In [223]:
# combining all datasets into one

In [224]:
df = deposit_summary.merge(withdrawal_summary, on = ['User Id', 'Date', 'Slot'], how= 'outer')

In [225]:
df.head()

,User Id,Date,Slot,deposit_amount,deposit_count,withdrawal_amount,withdrawal_count
0,2,2022-03-10,S1,NaN,NaN,117349.0,1.0
1,2,2022-05-10,S1,NaN,NaN,36000.0,1.0
2,2,2022-06-10,S1,40000.0,1.0,NaN,NaN
3,2,2022-08-10,S1,45000.0,2.0,NaN,NaN
4,2,2022-09-10,S1,NaN,NaN,11400.0,1.0

In [226]:
df = df.merge(gameplay_summary, on = ['User Id', 'Date', 'Slot'], how = 'outer')

In [227]:
df.head(10)

,User Id,Date,Slot,deposit_amount,deposit_count,withdrawal_amount,withdrawal_count,games_played
0,0,2022-06-10,S1,NaN,NaN,NaN,NaN,1.0
1,0,2022-10-10,S1,NaN,NaN,NaN,NaN,1.0
2,0,2022-10-17,S1,NaN,NaN,NaN,NaN,1.0
3,0,2022-10-22,S1,NaN,NaN,NaN,NaN,1.0
4,0,2022-10-23,S1,NaN,NaN,NaN,NaN,1.0
5,0,2022-10-26,S1,NaN,NaN,NaN,NaN,1.0
6,0,2022-10-28,S1,NaN,NaN,NaN,NaN,1.0
7,0,2022-10-29,S1,NaN,NaN,NaN,NaN,1.0
8,1,2022-01-10,S1,NaN,NaN,NaN,NaN,1.0
9,1,2022-07-10,S1,NaN,NaN,NaN,NaN,1.0

In [228]:
df.fillna(0, inplace= True)

In [229]:
df.head(10)

,User Id,Date,Slot,deposit_amount,deposit_count,withdrawal_amount,withdrawal_count,games_played
0,0,2022-06-10,S1,0.0,0.0,0.0,0.0,1.0
1,0,2022-10-10,S1,0.0,0.0,0.0,0.0,1.0
2,0,2022-10-17,S1,0.0,0.0,0.0,0.0,1.0
3,0,2022-10-22,S1,0.0,0.0,0.0,0.0,1.0
4,0,2022-10-23,S1,0.0,0.0,0.0,0.0,1.0
5,0,2022-10-26,S1,0.0,0.0,0.0,0.0,1.0
6,0,2022-10-28,S1,0.0,0.0,0.0,0.0,1.0
7,0,2022-10-29,S1,0.0,0.0,0.0,0.0,1.0
8,1,2022-01-10,S1,0.0,0.0,0.0,0.0,1.0
9,1,2022-07-10,S1,0.0,0.0,0.0,0.0,1.0

In [230]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19529 entries, 0 to 19528
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User Id            19529 non-null  int64
 1   Date               19529 non-null  object
 2   Slot               19529 non-null  object
 3   deposit_amount     19529 non-null  float64
 4   deposit_count      19529 non-null  float64
 5   withdrawal_amount  19529 non-null  float64
 6   withdrawal_count   19529 non-null  float64
 7   games_played       19529 non-null  float64
dtypes: float64(5), int64(1), object(2)
memory usage: 1.2+ MB

In [233]:
df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')

In [234]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19529 entries, 0 to 19528
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User Id            19529 non-null  int64
 1   Date               19529 non-null  datetime64[ns]
 2   Slot               19529 non-null  object
 3   deposit_amount     19529 non-null  float64
 4   deposit_count      19529 non-null  float64
 5   withdrawal_amount  19529 non-null  float64
 6   withdrawal_count   19529 non-null  float64
 7   games_played       19529 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(1)
memory usage: 1.2+ MB

### Loyalty Points Calculation

In [235]:
df['loyalty_points'] = (
    0.01 * df['deposit_amount'] + 
    0.005 * df['withdrawal_amount'] + 
    0.001 * np.maximum(df['deposit_count'] -df['withdrawal_count'], 0) + 
    0.2 * df['games_played']
)

### Q1. Slot wise Analysis

#### Loyalty points for specific dates and Slots
#### Calculating player wise loyalty points for given dates and slots.

In [240]:
result_q1 = df[
    ((df['Date'] == '2022-10-02') & (df['Slot'] == 'S1')) |
    ((df['Date'] == '2022-10-16') & (df['Slot'] == 'S2')) |
    ((df['Date'] == '2022-10-18') & (df['Slot'] == 'S1')) |
    ((df['Date'] == '2022-10-26') & (df['Slot'] == 'S2'))
]

In [241]:
result_q1.head()

,User Id,Date,Slot,deposit_amount,deposit_count,withdrawal_amount,withdrawal_count,games_played,loyalty_points
26,2,2022-10-18,S1,0.0,0.0,0.0,0.0,2.0,0.4
52,3,2022-10-18,S1,0.0,0.0,0.0,0.0,2.0,0.4
82,5,2022-10-18,S1,0.0,0.0,0.0,0.0,8.0,1.6
128,7,2022-10-18,S1,0.0,0.0,0.0,0.0,3.0,0.6
153,8,2022-10-18,S1,0.0,0.0,0.0,0.0,9.0,1.8

### Q2. Monthly Leaderboard

In [242]:
leaderboard = df.groupby('User Id').agg(total_points = ('loyalty_points', 'sum'), 
                                        total_games=('games_played', 'sum')
                                       ).reset_index()

In [243]:
leaderboard = leaderboard.sort_values(by=['total_points', 'total_games'], ascending = False)

In [262]:
leaderboard.head(50)

     User Id  total_points  total_games
631      634     45576.045         14.0
98        99     14798.362          2.0
563      566     11267.434         86.0
735      740      9756.551          0.0
709      714      9353.616          3.0
668      672      9024.562          4.0
210      212      8974.923          0.0
566      569      8489.916         10.0
220      222      7954.370          6.0
419      421      7891.420        802.0
584      587      7665.846        369.0
160      162      7464.200          1.0
206      208      7321.901        244.0
350      352      7182.473        147.0
363      365      7147.842       1775.0
780      786      6629.513          5.0
913      920      6402.657        436.0
236      238      6401.322        464.0
30        30      6321.624          8.0
536      538      6146.405         18.0
367      369      6046.215         18.0
982      989      5726.806       1684.0
304      306      5715.739          1.0
985      992      5615.948       1205.0
28        28      5603.825         19.0
908      915      5343.969          3.0
513      515      5343.809        219.0
413      415      5327.501         10.0
971      978      5228.914         38.0
598      601      5204.802         24.0
2          2      5095.270         45.0
616      619      4700.209          1.0
243      245      4485.512          0.0
677      681      4421.038          5.0
77        78      4032.310        274.0
969      976      4000.210          1.0
436      438      4000.202          1.0
943      950      3978.155          3.0
683      687      3905.227        857.0
198      200      3900.583          3.0
180      182      3828.531       1186.0
544      547      3813.468        628.0
92        93      3763.540        241.0
942      949      3589.887          0.0
596      599      3454.379          5.0
16        16      3435.591       1083.0
292      294      3357.806          4.0
952      959      3304.440          7.0
151      153      3231.726         24.0
257      259      3200.548         60.0

### Key Metrics

### Q3. Average Deposit Amount

In [256]:
avg_deposit = deposit['Amount'].sum()/deposit.shape[0]

In [258]:
print("Average Deposit: ", avg_deposit)

Average Deposit:  5492.4716407638925

### Q4. Avg Deposit Per User

In [ ]:
avg_deposit_user = deposit['Amount'].sum()/deposit['User Id'].nunique()

In [259]:
print("Avg Deposit per user: ", avg_deposit_user)

Avg Deposit per user:  104669.10163934426

### Q5. Avg Games Per User

In [260]:
avg_games = gameplay.shape[0]/gameplay['User Id'].nunique()

In [261]:
print("Avg games per user: ", avg_games)

Avg games per user:  341.53

#### Top 50 export in csv format

In [263]:
leaderboard.head(50).to_csv("top_50_players.csv", index= False)

#### Q1 Export slotwise analysed data

In [264]:
result_q1.to_csv("slotwise_loyalty.csv", index=False)

## Part B

### Bonus Allocation Strategy

After identifying the top 50 players based on loyalty points, a fair bonus distribution strategy is required for allocating ₹50,000.

#### Proposed Approach:

A hybrid model is recommended:

- 70% weight based on loyalty points (financial contribution)
- 30% weight based on number of games played (engagement)

#### Reasoning:

- Loyalty points capture both deposits and withdrawals
- Gameplay ensures active engagement is rewarded
- This prevents bias towards only high-spending users

#### Conclusion:

This hybrid approach ensures a balanced and fair distribution of bonus among top players.

## Part C

## Evaluation of Loyalty Formula

### Is the formula fair?

The current loyalty formula is partially fair but has some limitations:

- It favors users with higher deposits
- Players with high engagement but low deposits may receive fewer rewards

---

### Suggested Improvements:

1. Introduce a cap on deposit contribution to avoid dominance by high spenders  
2. Increase the weight of gameplay activity  
3. Normalize scores across users  
4. Add fraud detection mechanisms  

---

### Final Conclusion

The data was cleaned and analyzed properly, and loyalty points were calculated based on user activity. The analysis helped identify top players and showed that both gameplay and financial contribution impact user rewards. A balanced bonus strategy can further improve fairness and user engagement.